import Head from "next/head";
import { useState } from "react";
import Header from "../Components/Header";

import Products from './../Components/Products';

export async function getStaticProps() {
  const res = await fetch("https://fakestoreapi.com/products");

  const products = await res.json();
  return {
    props: {
      products,
    },
  };
}

export default function Home({ products }) {
  const [cartSize,setCartSize]=useState(0);
  return (
    <div className="p-10">
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header cartSize={cartSize}/>
      <Products products={products} setCartSize={setCartSize} cartSize={cartSize}/>
    </div>
  );
}
